### ISSUE TITLE
asyncio syntax error

### ISSUE THREAD

**Issue by gommdt** [adafruit/Adafruit_CircuitPython_asyncio#14]
While following the asyncio tutorial I am getting a syntax error.  I am using the"QT Py Haxpress" uf2.

async def read_color(curent_color): **<------  SyntaxError: invalid syntax**
    while True:
        r, g, b, c = apds.color_data
        print("Red: {0}, Green: {1}, Blue: {2}, Clear: {3}".format(r, g, b, c))
        curent_color.value = (r, g, b)
        await asyncio.sleep(0.2)

in the REPL:
> '>>>' import asyncio
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "asyncio/__init__.py", line 14, in <module>
    File "asyncio/core.py", line 15, in <module>
ImportError: no module named **'select'**
[code_py.zip](https://github.com/adafruit/Adafruit_CircuitPython_asyncio/files/7885291/code_py.zip)

**Comment by dhalbert** [comment]
The QT Py SAMD21 board, and all SAMD21 boards, do not have enough firmware space for async/await support. Sorry! Do you have another board, like an RP2040?

**Comment by gommdt** [comment]
Totally do.  I will try them out.  Thought I would be safe with the attached flash chip.

**Comment by gommdt** [comment]
Works like a charm on the QTPY RP2040. Thanks for the help!!!!
