### ISSUE TITLE
Incorporate fixes from https://github.com/micropython/micropython/pull/8459

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_asyncio#22]
* https://github.com/micropython/micropython/pull/8459

**Comment by jepler** [comment]
This is partially done in #30 but was incomplete.

**Comment by kbsriram** [comment]
I could be wrong, but should this bug be closed? I wasn't able to spot any changes from the original commit that aren't either in this library or the core. Maybe the remaining changes intended (adding tests to circuitpython core?) made its way there as part of https://github.com/adafruit/circuitpython/pull/8281 ?

**Comment by dhalbert** [comment]
@kbsriram I think you're right, since we updated quite recently when we merged recent versions of MicroPython. Thanks!
