### ISSUE TITLE
Releases zip files only contains examples now?

### ISSUE THREAD

**Issue by theboyknowsclass** [adafruit/Adafruit_CircuitPython_asyncio#27]
hi, can't seem to find the actual lib (since 0.5.13)

**Comment by Neradoc** [comment]
@tekktrik this looks like this is because `--package_folder_prefix "adafruit_, asyncio"` is no longer in the `circuitpython-build-bundles` call from the switch to pyproject.toml commit.

**Comment by dhalbert** [comment]
Fixing this issue https://github.com/adafruit/circuitpython-build-tools/issues/82 would also fix that.

**Comment by tekktrik** [comment]
The immediate fix is in for it now!  I've been meaning to learn more about the build tools, I'd love to take a look at the recently linked issue.

**Comment by tekktrik** [comment]
Closed via #28
